services:
  hero-app:
    container_name: hero-app-container
    build: .
    image: hero-app:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
